minishop/core/urls.py
from django.urls import path
from products import views as products_views

app_name = "core"

urlpatterns = [path("", products_views.HomeView.as_view(), name="home")]  # home 화면

minishop/minishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# 해당 프로젝트의 url 모음
urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("wishs/", include("wishs.urls", namespace="wishs")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("board/", include("board.urls", namespace="board")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minishop/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("<int:pk>/create/", views.create_order, name="create"),  # 주문 생성
    path("<int:pk>/detail/", views.order_detail, name="detail"),  # 주문 디테일
    path("<int:pk>/update/", views.order_update, name="update"),  # 주문 수정
    path("<int:pk>/delete/", views.order_delete, name="delete"),  # 주문 삭제
    path("manage/", views.OrderManageView.as_view(), name="manage"),  # 주문 관리 페이지
    path(
        "<int:pk>/delivery/", views.order_delivery, name="delivery"
    ),  # 주문 관리 (staff 유저가 배송처리함)
    path("my_order/", views.my_order_view, name="my_order"),  # 내가 한 주문
]

minishop/orders/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.db.models.fields import related

# Order 테이블
class Order(models.Model):

    """Order Model Definition"""

    # method는 select 할 수 있어, 이 셋 중 하나의 값을 가짐
    METHOD_CASH = "cash"
    METHOD_CARD = "card"
    METHOD_PAY = "pay"
    METHOD_CHOICES = (
        (METHOD_CASH, "Cash"),
        (METHOD_CARD, "Card"),
        (METHOD_PAY, "Pay"),
    )

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="orders"
    )  # 주문자 애트리뷰트 foreign key 가 사라지면 해당 객체도 삭제
    product = models.ForeignKey(
        "products.Product", on_delete=models.CASCADE, related_name="orders"
    )  # 상품 애트리뷰트 foreign key 가 사라지면 해당 객체도 삭제
    number = models.IntegerField(
        default=1, validators=[MinValueValidator(1)]
    )  # 주문 수량 애트리뷰트
    date_ordered = models.DateTimeField(auto_now_add=True)  # 주문 날짜 애트리뷰트
    method = models.CharField(
        max_length=4, choices=METHOD_CHOICES, default=METHOD_CASH
    )  # 결제방법 애트리뷰트
    address = models.TextField(null=False)  # 주소 애트리뷰트
    delivery = models.BooleanField(default=False)  # 배송 여부 애트리뷰트

    def __str__(self):
        return f"{self.user} - {self.product}"

    # 해당 테이블을 fk로 하는 reviews를 가져오는 함수
    def get_reviews(self):
        return self.reviews.all()

    # 해당 테이블을 fk로 하는 reviews가 있는지 확인해주는 함수
    def has_reviews(self):
        all_reviews = self.reviews.all()
        return len(all_reviews) > 0

    # AWS RDS 사용
    class Meta:
        managed = False
        db_table = "order"  # MySql에서 사용하는 테이블 이름

minishop/orders/forms.py
from django import forms
from . import models

# 주문을 생성해주는 폼
class CreateOrderForm(forms.ModelForm):
    class Meta:
        model = models.Order  # 해당 테이블의 인스턴스 생성
        fields = [  # 사용자가 입력할 애트리뷰트
            "number",
            "method",
            "address",
        ]

    # 폼 커스텀
    def __init__(self, *args, **kwargs):
        super(CreateOrderForm, self).__init__(*args, **kwargs)

        self.fields["number"].widget.attrs = {
            "class": "form-control",
            "id": "numberInput",
            "type": "number",
            "min": 1,
        }

        self.fields["method"].widget.attrs = {
            "class": "form-select",
            "id": "methodInput",
        }

        self.fields["address"].widget.attrs = {
            "class": "form-control",
            "id": "addressInput",
        }


# 주문을 수정해주는 폼
class UpdateOrderForm(forms.ModelForm):
    class Meta:
        model = models.Order  # 해당 테이블의 인스턴스가 수정됨
        fields = [  # 수정할 애트리뷰트
            "number",
            "method",
            "address",
        ]

    # 폼 커스텀
    def __init__(self, *args, **kwargs):
        super(UpdateOrderForm, self).__init__(*args, **kwargs)

        self.fields["number"].widget.attrs = {
            "class": "form-control",
            "id": "numberInput",
            "type": "number",
            "min": 1,
        }

        self.fields["method"].widget.attrs = {
            "class": "form-select",
            "id": "methodInput",
        }

        self.fields["address"].widget.attrs = {
            "class": "form-control",
            "id": "addressInput",
        }

minishop/orders/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView

from . import models
from . import forms

from users import mixins as users_mixins
from products import models as product_models

# 주문하기 함수
@login_required
def create_order(request, pk):
    try:
        if request.method == "POST":
            form = forms.CreateOrderForm(request.POST)
            product = product_models.Product.objects.get(pk=pk)
            if not product:
                return redirect(reverse("core:home"))
            if form.is_valid():
                with transaction.atomic():  # 모든 처리 과정 후, 재고 저장 및 주문 저장은 하나의 트랜잭션에서 관리
                    order = form.save(commit=False)
                    order.product = product
                    order.user = request.user
                    order.delivery = False
                    number = form.cleaned_data["number"]
                    product.inventory -= number  # 상품의 재고에서 수량만큼 뺌
                    if product.inventory < 0:  # 상품의 재고는 (-)가 될 수 없으므로 재고 에러를 발생시킴
                        raise InventoryException()
                    product.save()  # 재고가 (+) 라면 상품을 저장하고
                    order.save()  # 주문을 저장하는 것까지 하나의 트랜잭션에서 관리
                    messages.success(request, "product ordered")
                return redirect(reverse_lazy("products:detail", kwargs={"pk": pk}))

        else:
            form = forms.CreateOrderForm()
            product = product_models.Product.objects.get(pk=pk)
        return render(
            request,
            "orders/order_create.html",
            {"form": form, "pk": pk, "product": product},
        )
    # 재고 에러가 발생했다면
    except InventoryException:
        messages.error(request, "재고부족")
        return render(
            request,
            "orders/order_create.html",  # 주문 생성 폼에 머무르기
            {"form": form, "pk": pk, "product": product},
        )


# 재고부족 에러
class InventoryException(Exception):
    pass


# 내 주문 리스트 조회 리스트
@login_required
def my_order_view(request):
    user = request.user
    order_list = models.Order.objects.filter(user=user).order_by(
        "-date_ordered"
    )  # Order 테이블에서 user 애트리뷰트가 요청을 보낸 user와 같은 인스턴스만 가져온 후 최근에 주문한 것부터 가져옴
    paginator = Paginator(order_list, 15)
    page_num = request.GET.get("page")
    order_list = paginator.get_page(page_num)
    return render(request, "orders/order_list.html", {"order_list": order_list})


# 주문 디테일 조회 클래스
class OrderDetailView(users_mixins.LoggedInOnlyView, DetailView):

    model = models.Order


@login_required
def order_detail(request, pk):
    user = request.user
    order = models.Order.objects.get(pk=pk)  # 주문의 pk가 요청을 보낸 pk와 같은 인스턴스를 가져옴.
    if user == order.user or user.is_staff == True:  # 주문자와 staff유저만 해당 주문 디테일을 볼 수 있음.
        return render(request, "orders/order_detail.html", {"order": order})
    else:
        messages.error(request, "접근 권한이 없습니다.")
        return reverse_lazy("core:home")


# 주문 수정 함수
@login_required
def order_update(request, pk):
    order = models.Order.objects.get(pk=pk)
    product = product_models.Product.objects.get(
        pk=order.product.pk
    )  # order를 보낸 product pk로 product 테이블에서 인스턴스를 찾음
    try:
        if request.method == "POST":
            form = forms.UpdateOrderForm(request.POST)
            if not product:
                return redirect(reverse("core:home"))
            if form.is_valid():
                with transaction.atomic():  # 모든 처리 과정 후, 재고 저장 및 주문 저장은 하나의 트랜잭션에서 관리
                    # order = form.save(commit=False)
                    number = form.cleaned_data["number"]
                    method = form.cleaned_data["method"]
                    address = form.cleaned_data["address"]
                    product.inventory += order.number  # 이전에 주문한 수량만큼 product의 인벤토리에 추가함
                    product.inventory -= number  # 새로운 주문 수량만큼 product의 인벤토리에서 뺌
                    if product.inventory < 0:  # 재고량은 (-)가 될 수 없으므로 재고 에러를 냄
                        raise InventoryException()
                    order.method = method  # 폼 저장
                    order.address = address
                    order.number = number
                    product.save()
                    order.save()
                    messages.success(request, "주문이 수정되었습니다.")
                return redirect(reverse_lazy("orders:detail", kwargs={"pk": pk}))

        else:
            order = models.Order.objects.get(pk=pk)
            form = forms.UpdateOrderForm(instance=order)
        return render(
            request,
            "orders/order_update.html",
            {"form": form, "pk": pk, "product": product},
        )
    except InventoryException:  # 이 위와 같음
        messages.error(request, "재고부족")
        return render(
            request,
            "orders/order_update.html",
            {"form": form, "pk": pk, "product": product},
        )


# 주문 취소 함수
@login_required
def order_delete(request, pk):
    order = models.Order.objects.get(pk=pk)
    if order is None:
        messages.success(request, "주문이 존재하지 않습니다.")
    product = product_models.Product.objects.get(pk=order.product.pk)
    if product is None:
        order.delete()  # 해당하는 order 인스턴스 삭제
        return redirect(reverse_lazy("orders:my_order"))
    with transaction.atomic():  # 모든 처리 과정 후, 재고 저장 및 주문 저장은 하나의 트랜잭션에서 관리
        product.inventory += order.number  # 재고에 이전에 주문한 수량만큼 더해줌
        product.save()  # product 저장
        order.delete()  # 해당하는 order 인스턴스 삭제
        messages.success(request, "주문이 삭제되었습니다.")
    return redirect(reverse_lazy("orders:my_order"))


# order 관리 페이지
@method_decorator(staff_member_required, name="dispatch")  # staff 멤버만 접근 가능
class OrderManageView(ListView):
    model = models.Order
    paginate_by = 15
    paginate_orphans = 4
    ordering = "-date_ordered"  # 최근에 주문한 순서대로 정렬
    context_object_name = "order_list"
    template_name = "orders/order_manage.html"


# staff 멤버만 배송처리 가능
@staff_member_required
def order_delivery(request, pk):
    order = models.Order.objects.get(pk=pk)
    with transaction.atomic():  # 배송을 했지만 주문에 처리가 안 될 경우를 대비해 하나의 트랜젝션에서 관리
        order.delivery = True  # delivery 처리 함
        order.save()  # 주문서 저장
        messages.success(request, "배송처리가 완료되었습니다.")
    return redirect(reverse("orders:manage"))

minishop/templates/orders/order_create.html
{% extends 'base.html' %}
{% block page_title %}상품 주문{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    <div class="container-fluid d-flex flex-column justify-content-center align-center" style=" width:1000px;">
        <div class="mb-4 d-flex justify-content-between">
            <h3>상품 주문</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">

            <form action="." method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품명</span>
                            <input class="form-control bg-white" type="text" value="{{product.name}}"
                                aria-label="Disabled input example" disabled readonly>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">가격</span>
                            <input class="form-control bg-white" type="text" value="{{product.price}}"
                                aria-label="Disabled input example" disabled readonly>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">주문 수량</span>
                            {{form.number}}
                        </div>
                        {% if form.number.errors %}
                        {% for error in form.number.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">결제방법</span>
                            {{form.method}}
                            <div class="invalid-feedback">
                                결제방법을 선택해주세요.
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">주소</span>
                            {{form.address}}
                            <div class="invalid-feedback">
                                주소를 입력해주세요.
                            </div>
                        </div>
                    </div>

                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0">주문하기</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

minishop/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block page_title %}{{order.product.name}} 주문 상세{% endblock page_title %}
{% block content %}

<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>주문 상세정보</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table text-nowrap align-middle text-center w-100">
                    <tbody>
                        <tr>
                            <th class="table-secondary" style="width:200px">주문번호</th>
                            <td style="width:800px">{{order.pk}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 상품</th>
                            <td><a href="{% url 'products:detail' pk=order.product.pk %}"
                                    class="text-decoration-none text-black">{{order.product}}</a></td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 수량</th>
                            <td>{{order.number}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 날짜</th>
                            <td>{{order.date_ordered}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">결제 방법</th>
                            <td>{{order.method}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">배송 주소</th>
                            <td>{{order.address}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">배송 여부</th>
                            <td>
                                {% if order.delivery %}
                                배송 완료
                                {% else %}
                                배송 미완료
                                {% endif %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        {% if order.delivery %}
        <h5>배송이 완료되어 주문이 수정 및 취소 불가합니다.</h5>
        {% else %}
        <div class="d-flex justify-content-end">
            <div>
                <a href="{% url 'orders:update' pk=order.pk %}" class="btn btn-outline-dark flex-shrink-0">주문 수정하기</a>
            </div>
            <div class="ms-4">
                <a href="{% url 'orders:delete' pk=order.pk %}" class="btn btn-outline-dark flex-shrink-0">주문 취소하기</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

minishop/templates/orders/order_list.html
{% extends 'base.html' %}
{% block page_title %}내 주문정보{% endblock page_title %}
{% block content %}

<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>내 주문 내역</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table align-middle text-nowrap">
                    <thead>
                        <tr>
                            <th style="width:50px" class="text-center" scope="col">주문번호</th>
                            <th style="width:300px" class="text-center" scope="col">제품</th>
                            <th style="width:100px" class="text-center" scope="col">수량</th>
                            <th style="width:200px" class="text-center" scope="col">주문일</th>
                            <th style="width:100px" class="text-center" scope="col">배송</th>
                            <th style="width:200px" class="text-center" scope="col">리뷰</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_list %}
                        <tr>
                            <td class="text-center">
                                <a href="{% url 'orders:detail' pk=order.pk %}"
                                    class="text-decoration-none text-black">{{order.pk}}</a>
                            </td>
                            <td class="text-center">
                                <a class="text-decoration-none text-black"
                                    href="{% url 'products:detail' pk=order.product.pk %}">{{order.product}}</a>
                            </td>
                            <td class="text-center">
                                {{order.number}}</td>

                            <td class="text-center">
                                {{order.date_ordered.year}}.{{order.date_ordered.month}}.{{order.date_ordered.day}}</td>
                            <td class="text-center">
                                {{order.delivery}}</td>
                            <td>
                                <!-- 작성불가/리뷰작성/작성완료-->
                                <div class="text-center">
                                    {% if order.delivery == False %}
                                    <button class="btn btn-outline-dark flex-shrink-0 " disabled>
                                        작성불가</button>
                                    {% elif order.has_reviews %}
                                    <button class="btn btn-outline-dark flex-shrink-0 " disabled>
                                        작성완료</button>
                                    {% else %}
                                    <a href="{% url 'reviews:create' order_pk=order.pk %}"
                                        class="btn btn-outline-dark flex-shrink-0 ">
                                        리뷰작성</a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>



        <!-- Paginator -->
        <div class="d-flex justify-content-center">
            <ul class="pagination ">
                <!-- 이전 페이지 -->
                {% if order_list.has_previous %}
                <li class="page-item">
                    <a href="?page={{order_list.previous_page_number}}" class="page-link">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}


                <!-- 페이지 링크들 -->
                {% for n in order_list.paginator.page_range %}
                {% if order_list.number == n %}
                <li class="page-item active">
                    <span class="page-link">{{ n }}</span>
                </li>
                {% elif n > order_list.number|add:'-5' and n < order_list.number|add:'5' %} <li class="page-item"><a
                        class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 -->
                    {% if order_list.has_next %}
                    <li class="page-item">
                        <a href="?page={{order_list.next_page_number}}" class="page-link">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

minishop/templates/orders/order_manage.html
{% extends 'base.html' %}
{% block page_title %}스태프 페이지{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    {% include 'users/partials/staff_navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>주문 관리</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table align-middle text-nowrap">
                    <thead>
                        <tr>
                            <th style="width:50px" class="text-center" scope="col">주문번호</th>
                            <th style="width:150px" class="text-center" scope="col">주문자</th>
                            <th style="width:350px" class="text-center" scope="col">상품</th>
                            <th style="width:50px" class="text-center" scope="col">수량</th>
                            <th style="width:150px" class="text-center" scope="col">주문 날짜</th>
                            <th style="width:50px" class="text-center" scope="col">결제 방식</th>
                            <th style="width:100px" class="text-center" scope="col">배송 여부</th>
                            <th style="width:100px" class="text-center" scope="col">배송 처리</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_list %}
                        <tr>
                            <td class="text-center text-decoration-none"><a href="{% url 'orders:detail' pk=order.pk %}"
                                    class=" text-decoration-none text-black fw-bolder">{{order.pk}}</a></td>
                            <td class="text-center text-decoration-none">{{order.user.nickname}}</td>
                            <td class="text-center"><a href="{% url 'products:detail' pk=order.product.pk %}"
                                    class=" text-decoration-none text-black ">{{order.product}}</a></td>
                            <td class="text-center">{{order.number}}</td>
                            <td class="text-center">
                                {{order.date_ordered.year}}.{{order.date_ordered.month}}.{{order.date_ordered.day}}</td>
                            <td class="text-center">{{order.method}}</td>
                            <td class="text-center">
                                {{order.delivery}}</td>
                            {% if order.delivery %}
                            <td class="text-center">
                                <button class="btn btn-outline-dark flex-shrink-0" disabled>
                                    완료</button>
                            </td>
                            {% else %}
                            <td class="text-center"><a href="{% url 'orders:delivery' pk=order.pk %}"
                                    class="btn btn-outline-dark flex-shrink-0">
                                    처리</a>
                            </td>
                            {% endif %}


                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>




        <!-- Paginator -->
        <div class="d-flex justify-content-center">
            <ul class="pagination ">
                <!-- 이전 페이지 -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}


                <!-- 페이지 링크들 -->
                {% for n in page_obj.paginator.page_range %}
                {% if page_obj.number == n %}
                <li class="page-item active">
                    <span class="page-link">{{ n }}</span>
                </li>
                {% elif n > page_obj.number|add:'-5' and n < page_obj.number|add:'5' %} <li class="page-item"><a
                        class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

minishop/templates/orders/order_update.html
{% extends 'base.html' %}
{% block page_title %}주문 수정{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>주문 상세정보 수정</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">

            <form action="." method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품명</span>
                            <input class="form-control bg-white" type="text" value="{{product.name}}"
                                aria-label="Disabled input example" disabled readonly>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">가격</span>
                            <input class="form-control bg-white" type="text" value="{{product.price}}"
                                aria-label="Disabled input example" disabled readonly>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">주문 수량</span>
                            {{form.number}}
                        </div>
                        {% if form.number.errors %}
                        {% for error in form.number.errors %}
                        <span class="text-red-700 font-medium text-sm">{{error}}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">결제방법</span>
                            {{form.method}}
                            <div class="invalid-feedback">
                                결제방법을 선택해주세요.
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">주소</span>
                            {{form.address}}
                            <div class="invalid-feedback">
                                주소를 입력해주세요.
                            </div>
                        </div>
                    </div>

                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0">수정하기</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}