minishop/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("", views.FAQListView.as_view(), name="list"),  # faq 글 목록
    path("create/", views.faq_post_create, name="create"),  # faq 글 생성
    path("my_faq/", views.my_faqpost_view, name="my_faq"),  # 내가 작성한 faq 글 목록
    path("<int:pk>/detail/", views.faq_post_detail, name="detail"),  # faq 글 상세히 보기
    path("<int:pk>/update/", views.faq_post_update, name="update"),  # faq 글 수정
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name="delete"),  # faq 글 삭제
    path(
        "<int:pk>/comment_create/", views.faqcomment_create, name="comment_create"
    ),  # faq 답글 작성
]

minishop/core/urls.py
from django.urls import path
from products import views as products_views

app_name = "core"

urlpatterns = [path("", products_views.HomeView.as_view(), name="home")]  # home 화면

minishop/minishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# 해당 프로젝트의 url 모음
urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("wishs/", include("wishs.urls", namespace="wishs")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("board/", include("board.urls", namespace="board")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minishop/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("<int:pk>/create/", views.create_order, name="create"),  # 주문 생성
    path("<int:pk>/detail/", views.order_detail, name="detail"),  # 주문 디테일
    path("<int:pk>/update/", views.order_update, name="update"),  # 주문 수정
    path("<int:pk>/delete/", views.order_delete, name="delete"),  # 주문 삭제
    path("manage/", views.OrderManageView.as_view(), name="manage"),  # 주문 관리 페이지
    path(
        "<int:pk>/delivery/", views.order_delivery, name="delivery"
    ),  # 주문 관리 (staff 유저가 배송처리함)
    path("my_order/", views.my_order_view, name="my_order"),  # 내가 한 주문
]

minishop/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("my_info/", views.my_info, name="my_info"),  # 내 정보 보기
    path("logout/", views.logout_view, name="logout"),  # 로그아웃
    path("login/", views.UserLoginView.as_view(), name="login"),  # 로그인
    path("sign_up/", views.SignUpView.as_view(), name="sign_up"),  # 회원가입
    path("update/", views.UserUpdateView.as_view(), name="update"),  # 회원정보 수정
]

minishop/wishs/urls.py
from django.urls import path

from . import views

app_name = "wishs"

urlpatterns = [
    path("<int:pk>/add/", views.add_wish, name="add"),  # 찜 하기
    path("<int:pk>/delete/", views.delete_wish, name="delete"),  # 찜 취소
    path("my_wish/", views.my_wish_view, name="my_wish"),  # 내가 찜한 목록
]

minishop/templates/partials/footer.html
{% load static %}
<footer class="footer mt-auto py-3">
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <p class="col-md-4 mb-0 text-muted">2021-2 HUFS 데베로 조인</p>

            <img src="{% static 'logo.png' %}" style="width:40px;height:auto;">

            <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item px-2">
                    <span class="text-muted">김소연</span>
                </li>
                <li class="nav-item px-2">
                    <span class="text-muted">정나윤</span>
                </li>
                <li class="nav-item px-2">
                    <span class="text-muted">김현</span>
                </li>
                <li class="nav-item px-2">
                    <span class="text-muted">박주하</span>
                </li>
            </ul>
        </footer>
    </div>
</footer>

minishop/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'core:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'core:home' %}">상품</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'board:list' %}">FAQ</a></li>
            </ul>
            <ul class="navbar-nav d-flex">
                {% if user.is_authenticated %}
                {% if user.is_active and user.is_staff %}
                <li class="nav-item"><a class="nav-link" href="{% url 'products:manage' %}">STAFF ONLY</a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">마이페이지</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'users:my_info'%}">마이페이지</a></li>
                        <li><a class="dropdown-item" href="{% url 'wishs:my_wish' %}">찜한 목록</a></li>
                        <li>
                            <hr class="dropdown-divider" />
                        </li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'users:sign_up' %}">회원가입</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>