minishop/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path("", views.FAQListView.as_view(), name="list"),  # faq 글 목록
    path("create/", views.faq_post_create, name="create"),  # faq 글 생성
    path("my_faq/", views.my_faqpost_view, name="my_faq"),  # 내가 작성한 faq 글 목록
    path("<int:pk>/detail/", views.faq_post_detail, name="detail"),  # faq 글 상세히 보기
    path("<int:pk>/update/", views.faq_post_update, name="update"),  # faq 글 수정
    path("<int:pk>/delete/", views.DeletePostView.as_view(), name="delete"),  # faq 글 삭제
    path(
        "<int:pk>/comment_create/", views.faqcomment_create, name="comment_create"
    ),  # faq 답글 작성
]

minishop/core/urls.py
from django.urls import path
from products import views as products_views

app_name = "core"

urlpatterns = [path("", products_views.HomeView.as_view(), name="home")]  # home 화면

minishop/minishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# 해당 프로젝트의 url 모음
urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("wishs/", include("wishs.urls", namespace="wishs")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("board/", include("board.urls", namespace="board")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minishop/reviews/urls.py
from django.urls import path

from . import views

app_name = "reviews"

urlpatterns = [
    path("<int:order_pk>/create", views.review_create, name="create"),  # 리뷰 생성
    path("<int:pk>/update", views.ReviewUpdate.as_view(), name="update"),  # 리뷰 수정
    path("<int:pk>/delete", views.DeleteReviewView.as_view(), name="delete"),  # 리뷰 삭제
    path("my_review", views.my_review_view, name="my_review"),  # 내가 작성한 리뷰 보기
]

minishop/reviews/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Review 테이블
class Review(models.Model):

    """Review Model Definition"""

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="reviews"
    )  # 리뷰 작성자 애트리뷰트 foreign key 가 사라지면 해당 객체도 삭제
    order = models.ForeignKey(
        "orders.Order", on_delete=models.CASCADE, related_name="reviews"
    )  # 리뷰가 작성되는 주문 애트리뷰트 foreign key 가 사라지면 해당 객체도 삭제
    product = models.ForeignKey(
        "products.Product",
        on_delete=models.CASCADE,
        related_name="reviews",
    )  # 리뷰가 작성되는 상품 애트리뷰트 foreign key 가 사라지면 해당 객체도 삭제
    review = models.TextField()  # 리뷰 내용 애트리뷰트
    created_at = models.DateTimeField(auto_now_add=True)  # 리뷰 작성 날짜 애트리뷰트
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )  # 리뷰 rating 애트리뷰트, 최소 1, 최대 5의 정수값을 가짐

    # AWS RDS 사용
    class Meta:
        managed = False
        db_table = "review"  # MySql에서 사용하는 테이블 이름

minishop/reviews/forms.py
from django import forms

from . import models

# 리뷰 생성 폼
class CreateReviewForm(forms.ModelForm):
    class Meta:
        model = models.Review  # 해당 테이블의 인스턴스 생성
        fields = ("review", "rating")

    def __init__(self, *args, **kwargs):
        super(CreateReviewForm, self).__init__(*args, **kwargs)

        self.fields["review"].widget.attrs = {
            "class": "form-control",
            "id": "reviewInput",
            "style": "height: 100px",
            "placeholder": "리뷰를 작성해주세요",
        }
        self.fields["rating"].widget.attrs = {
            "class": "form-control",
            "id": "ratingInput",
            "max": 5,
            "min": 1,
        }

minishop/reviews/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView, DeleteView

from . import forms
from . import models
from users import mixins as users_mixins
from orders import models as order_models


# 리뷰 생성 함수
@login_required
def review_create(request, order_pk):
    order = order_models.Order.objects.get(
        pk=order_pk
    )  # order table에서 pk값으로 필요한 인스턴스를 가져옴
    user = request.user  # user는 요청을 보낸 유저
    if order.user != user:  # order 에 fk로 있는 user와 요청을 보낸 유저가 다르다면
        messages.error(request, "접근 권한이 없습니다.")  # 에러 == 리뷰 생성 불가
        return redirect("core:home")
    if request.method == "POST":
        form = forms.CreateReviewForm(request.POST)  # 사용자가 입력한 폼을 가져옴
        if form.is_valid():
            finished_form = form.save(commit=False)
            finished_form.user = request.user  # 폼에 없는 요소들을 채워줌
            finished_form.order = order
            finished_form.product = order.product
            finished_form.save()
            return redirect("reviews:my_review")
    else:
        form = forms.CreateReviewForm()
    return render(request, "reviews/review_create.html", {"form": form, "order": order})


# 내가 작성한 리뷰들을 봄
@login_required
def my_review_view(request):
    user = request.user
    review_list = models.Review.objects.filter(user=user).order_by(
        "-created_at"
    )  # review에서 user가 요청을 보낸 유저와 같은 리뷰를 가져와 최근에 작성한 순으로 정렬
    paginator = Paginator(review_list, 15)
    page_num = request.GET.get("page")
    review_list = paginator.get_page(page_num)
    return render(request, "reviews/review_list.html", {"review_list": review_list})


# 리뷰 수정 클래스
class ReviewUpdate(users_mixins.LoggedInOnlyView, UpdateView):

    model = models.Review  # 해당 테이블의 인스턴스를 수정함
    template_name = "reviews/review_update.html"
    fields = ("review", "rating")  # 사용자가 입력할 필드

    # object 가져오기
    def get_object(self, queryset=None):
        review = super().get_object(queryset=queryset)
        if review.user.pk != self.request.user.pk:  # review를 작성한 유저와 요청을 보낸 유저가 다르면
            return redirect("core:home")  # 홈으로 감
        return review

    def get_success_url(self):
        return reverse("reviews:my_review")

    # 폼 입력 커스텀
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["review"].widget.attrs = {
            "placeholder": "리뷰 입력",
            "class": "form-control",
            "id": "reviewInput",
            "aria-describedby": "reviewInput",
            "aria-label": "Review",
            "type": "text",
        }
        form.fields["rating"].widget.attrs = {
            "class": "form-control",
            "id": "ratingInput",
            "aria-describedby": "ratingInput",
            "aria-label": "Rating",
            "min": 1,
            "max": 5,
        }
        return form


# 리뷰 삭제 클래스
class DeleteReviewView(users_mixins.LoggedInOnlyView, DeleteView):

    model = models.Review  # 해당 테이블의 인스턴스 삭제
    context_object_name = "reviews"

    # 성공 시 redirect 할 url
    def get_success_url(self):
        return reverse_lazy("reviews:my_review")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

minishop/templates/reviews/review_create.html
{% extends 'base.html' %}
{% block page_title %}리뷰 작성{% endblock page_title %}
{% block content %}

<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>리뷰 작성</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table text-nowrap align-middle text-center w-100">
                    <tbody>
                        <tr>
                            <th class="table-secondary" style="width:200px">주문번호</th>
                            <td style="width:800px">{{order.pk}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 상품</th>
                            <td><a href="{% url 'products:detail' pk=order.product.pk %}"
                                    class="text-decoration-none text-black">{{order.product}}</a></td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 날짜</th>
                            <td>{{order.date_ordered}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div>
            <form action="{% url 'reviews:create' order_pk=order.pk %}" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{form.review}}
                    <label for="review">리뷰 작성</label>
                </div>
                <div class="col mb-3">
                    <div class="input-group has-validation">
                        <span class="input-group-text">별점</span>
                        {{form.rating}}
                        <span class="input-group-text">1에서 5사이</span>
                    </div>
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0 ">리뷰작성</button>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}

minishop/templates/reviews/review_list.html
{% extends 'base.html' %}
{% block page_title %}내 리뷰{% endblock page_title %}
{% block content %}

<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>내 리뷰 내역</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table align-middle text-nowrap">
                    <thead>
                        <tr>
                            <th style="width:25px" class="text-center" scope="col">주문번호</th>
                            <th style="width:200px" class="text-center" scope="col">제품</th>
                            <th style="width:500px" class="text-center" scope="col">리뷰</th>
                            <th style="width:25px" class="text-center" scope="col">별점</th>
                            <th style="width:200px" class="text-center" scope="col">작성일</th>
                            <th style="width:100px" class="text-center" scope="col">수정</th>
                            <th style="width:100px" class="text-center" scope="col">삭제</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for review in review_list %}
                        <tr>
                            <td class="text-center">
                                <a href="{% url 'orders:detail' pk=review.order.pk %}"
                                    class="text-decoration-none text-black">{{review.order.pk}}</a>
                            </td>
                            <td class="text-center">
                                <a class="text-decoration-none text-black"
                                    href="{% url 'products:detail' pk=review.product.pk %}">{{review.order.product}}</a>

                            </td>
                            <td class="text-center">
                                {{review.review}}</td>

                            <td class="text-center">
                                {{review.rating}}
                            </td>
                            <td class="text-center">
                                {{review.created_at.year}}.{{review.created_at.month}}.{{review.created_at.day}}
                            </td>
                            <td class="text-center"><a href="{% url 'reviews:update' pk=review.pk %}"
                                    class="btn btn-outline-dark flex-shrink-0">
                                    수정</a>
                            </td>
                            <td class="text-center"><a href="{% url 'reviews:delete' pk=review.pk %}"
                                    class="btn btn-outline-danger flex-shrink-0 ">
                                    삭제</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>



        <!-- Paginator -->
        <div class="d-flex justify-content-center">
            <ul class="pagination ">
                <!-- 이전 페이지 -->
                {% if review_list.has_previous %}
                <li class="page-item">
                    <a href="?page={{review_list.previous_page_number}}" class="page-link">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}


                <!-- 페이지 링크들 -->
                {% for n in review_list.paginator.page_range %}
                {% if review_list.number == n %}
                <li class="page-item active">
                    <span class="page-link">{{ n }}</span>
                </li>
                {% elif n > review_list.number|add:'-5' and n < review_list.number|add:'5' %} <li class="page-item"><a
                        class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 -->
                    {% if review_list.has_next %}
                    <li class="page-item">
                        <a href="?page={{review_list.next_page_number}}" class="page-link">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

minishop/templates/reviews/review_update.html
{% extends 'base.html' %}
{% block page_title %}리뷰 수정{% endblock page_title %}
{% block content %}

<div class="d-flex container mt-5">
    {% include 'users/partials/navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4">
            <h3>리뷰 수정</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table text-nowrap align-middle text-center w-100">
                    <tbody>
                        <tr>
                            <th class="table-secondary" style="width:200px">주문번호</th>
                            <td style="width:800px">{{review.order.pk}}</td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 상품</th>
                            <td><a href="{% url 'products:detail' pk=review.order.product.pk %}"
                                    class="text-decoration-none text-black">{{review.order.product}}</a></td>
                        </tr>
                        <tr>
                            <th class="table-secondary">주문 날짜</th>
                            <td>{{review.order.date_ordered}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div>
            <form action="{% url 'reviews:update' pk=review.pk %}" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    {{form.review}}
                    <label for="reviewInput">리뷰 수정</label>
                </div>
                <div class="col mb-3">
                    <div class="input-group has-validation">
                        <span class="input-group-text">별점</span>
                        {{form.rating}}
                        <span class="input-group-text">1에서 5사이</span>
                    </div>
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0 ">리뷰수정</button>
                </div>
            </form>
        </div>


    </div>
</div>
{% endblock %}