minishop/core/urls.py
from django.urls import path
from products import views as products_views

app_name = "core"

urlpatterns = [path("", products_views.HomeView.as_view(), name="home")]  # home 화면

minishop/minishop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# 해당 프로젝트의 url 모음
urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("wishs/", include("wishs.urls", namespace="wishs")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("board/", include("board.urls", namespace="board")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minishop/products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("<int:pk>/", views.product_detail_view, name="detail"),  # 상품 디테일
    path("create/", views.CreateProductView.as_view(), name="create"),  # 상품 생성
    path("<int:pk>/update/", views.UpdateProductView.as_view(), name="update"),  # 상품 수정
    path("<int:pk>/delete/", views.DeleteProductView.as_view(), name="delete"),  # 상품 삭제
    path("manage/", views.ProductManageView.as_view(), name="manage"),  # 상품 관리페이지
]

minishop/wishs/urls.py
from django.urls import path

from . import views

app_name = "wishs"

urlpatterns = [
    path("<int:pk>/add/", views.add_wish, name="add"),  # 찜 하기
    path("<int:pk>/delete/", views.delete_wish, name="delete"),  # 찜 취소
    path("my_wish/", views.my_wish_view, name="my_wish"),  # 내가 찜한 목록
]

minishop/products/models.py
import random
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

# 상품 카테고리 테이블
class ProductCategory(models.Model):

    """Product Category Model Definition"""

    name = models.CharField(max_length=50)  # 이름 애트리뷰트

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Product Categories"

        # AWS RDS 사용
        managed = False
        db_table = "category"  # MySql에서 사용하는 테이블 이름


# 상품 사진 이름 커스텀을 위한 함수
def product_directory_path(instance, filename):
    n = random.randint(1000000000, 9999999999)
    return "product/product_{}{}/{}".format(instance.id, n, filename)


# Product 테이블
class Product(models.Model):

    """Product Model Definition"""

    name = models.CharField(max_length=100)  # 이름 애트리뷰트
    price = models.IntegerField(validators=[MinValueValidator(1)])  # 가격 애트리뷰트
    inventory = models.PositiveIntegerField(
        validators=[MinValueValidator(0)]
    )  # 재고 애트리뷰트, 최소 0의 값을 가짐
    description = models.TextField()  # 설명 애트리뷰트
    category = models.ForeignKey(
        "ProductCategory",
        related_name="products",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )  # 카테고리 애트리뷰트, 앞서 만든 category 테이블의 값을 fk로 가짐
    photo = models.ImageField(
        blank=True, null=True, upload_to=product_directory_path
    )  # 사진 애트리뷰트
    created_at = models.DateTimeField(auto_now_add=True)  # 상품 생성 날짜 애트리뷰트
    discontinue = models.BooleanField(default=False)  # 단종여부 애트리뷰트

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk": self.pk})

    # 해당 product의 별점을 구함
    def total_rating(self):
        all_reviews = self.reviews.all()  # 해당 테이블을 fk로 가지는 reviews 테이블의 인스턴스를 가져옴
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += (
                    review.rating
                )  # review테이블의 rating 애트리뷰트의 값 만큼 all_rating에 더해줌
            return round(all_ratings / len(all_reviews), 2)
        return 0

    # AWS RDS 사용
    class Meta:
        managed = False
        db_table = "product"  # MySql에서 사용하는 테이블 이름

minishop/products/forms.py
from django import forms

from . import models

# 상품을 생성해주는 폼
class CreateProductForm(forms.ModelForm):
    class Meta:
        model = models.Product  # 해당 테이블의 인스턴스 생성
        fields = (  # 사용자가 입력할 폼
            "name",
            "price",
            "inventory",
            "description",
            "category",
            "photo",
        )

    # 폼 커스텀
    def __init__(self, *args, **kwargs):
        super(CreateProductForm, self).__init__(*args, **kwargs)

        self.fields["name"].widget.attrs = {
            "class": "form-control",
            "id": "numberInput",
            "type": "number",
        }

        self.fields["price"].widget.attrs = {
            "class": "form-select",
            "id": "priceInput",
            "min": 0,
        }

        self.fields["inventory"].widget.attrs = {
            "class": "form-control",
            "id": "inventoryInput",
            "min": 0,
        }
        self.fields["description"].widget.attrs = {
            "class": "form-control",
            "id": "descriptionInput",
        }
        self.fields["category"].widget.attrs = {
            "class": "form-select",
            "id": "categoryInput",
        }
        self.fields["photo"].widget.attrs = {
            "class": "form-control",
            "id": "photoInput",
        }

minishop/products/views.py
from django.contrib.auth.models import AnonymousUser
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
)

from . import models
from . import forms
from users import mixins as users_mixins
from wishs import models as wishs_models
from reviews import models as reviews_model

# 홈 페이지.
class HomeView(ListView):

    """HomeView Definition"""

    model = models.Product  # 해당 테이블의 값을 가져옴
    paginate_by = 12
    paginate_orphans = 4
    ordering = "-created_at"
    context_object_name = "products"


# 상품 상세페이지
def product_detail_view(request, pk):
    user = request.user
    product = models.Product.objects.get(pk=pk)
    if user != AnonymousUser():  # 만약 비로그인 회원이 아니라면
        try:
            wishs_models.Wish.objects.get(
                user=user, product=product
            )  # wish 테이블에서 user=user, product=product인 인스턴스를 가져옴
            is_wish = True  # 가져오면 찜하기는 true
        except wishs_models.Wish.DoesNotExist:  # 만약 위의 그러한 인스턴스가 없다면
            is_wish = False  # 찜하기는 false
    else:  # 비로그인 회원이라면
        is_wish = False  # 찜하기는 false
    reviews = reviews_model.Review.objects.filter(
        product=product
    )  # reviews 테이블에서 product=product 인 인스턴스를 가져옴
    return render(
        request,
        "products/product_detail.html",
        {"product": product, "is_wish": is_wish, "reviews": reviews},
    )


# 상품 생성 클래스. staff 유저만 접근 가능
@method_decorator(staff_member_required, name="dispatch")
class CreateProductView(CreateView):

    """Product Create View Definition"""

    model = models.Product  # 연결할 클래스 or table명
    context_object_name = "product"  # context 변수명 지정
    form_class = forms.CreateProductForm  # 우리가 만든 폼 클래스를 form_class에 할당!
    template_name = "products/product_create.html"

    def get_success_url(self):
        return reverse("products:detail", kwargs={"pk": self.object.pk})


# 상품 수정 클래스. 위와 동일하게 staff 멤버만 접근 가능
@method_decorator(staff_member_required, name="dispatch")
class UpdateProductView(users_mixins.LoggedInOnlyView, UpdateView):

    model = models.Product  # 해당 테이블의 인스턴스 수정
    template_name = "products/product_update.html"
    fields = (
        "name",
        "price",
        "inventory",
        "description",
        "category",
        "photo",
        "discontinue",
    )
    success_message = "상품이 수정되었습니다"

    # 폼 입력 커스텀
    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields["name"].widget.attrs = {
            "placeholder": "상품명",
            "class": "form-control",
            "id": "nameInput",
            "aria-describedby": "nameInput",
            "aria-label": "Name",
            "type": "text",
        }
        form.fields["price"].widget.attrs = {
            "class": "form-control",
            "id": "priceInput",
            "aria-describedby": "priceInput",
            "aria-label": "Price",
            "min": 0,
        }
        form.fields["inventory"].widget.attrs = {
            "class": "form-control",
            "id": "inventoryInput",
            "aria-describedby": "inventoryInput",
            "aria-label": "Inventory",
            "min": 0,
        }
        form.fields["description"].widget.attrs = {
            "class": "form-control",
            "id": "descriptionInput",
            "aria-describedby": "descriptionInput",
            "aria-label": "Description",
        }
        form.fields["category"].widget.attrs = {
            "class": "form-select",
            "id": "categoryInput",
            "aria-describedby": "categoryInput",
            "aria-label": "Category",
        }
        form.fields["photo"].widget.attrs = {
            "class": "form-control",
            "id": "photoInput",
        }

        form.fields["discontinue"].widget.attrs = {
            "class": "form-check-input",
            "type": "checkbox",
            "id": "discontinueInput",
            "aria-describedby": "discontinueInput",
            "aria-label": "Discontinue",
        }
        return form

    def get_success_url(self):
        return reverse("products:manage")


# 상품 삭제 클래스. 위와 동일
@method_decorator(staff_member_required, name="dispatch")
class DeleteProductView(users_mixins.LoggedInOnlyView, DeleteView):

    model = models.Product  # 해당 테이블의 인스턴스 삭제
    context_object_name = "product"

    def get_success_url(self):
        return reverse_lazy("products:manage")

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


# 상품 관리 클래스
@method_decorator(staff_member_required, name="dispatch")
class ProductManageView(ListView):

    model = models.Product  # 해당 테이블의 인스턴스 관리
    paginate_by = 15
    paginate_orphans = 4
    ordering = "-created_at"  # 최근 생성된 상품 순으로 정렬
    context_object_name = "product_list"
    template_name = "products/product_manage.html"

minishop/templates/products/product_create.html
{% extends 'base.html' %}
{% block page_title %}상품 추가{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    {% include 'users/partials/staff_navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4 d-flex justify-content-between">
            <h3>상품 추가</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">

            <form action="." method="post" enctype="multipart/form-data">

                {% csrf_token %}
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품명</span>
                            {{form.name}}
                            <div class="invalid-feedback">
                                상품명을 입력해주세요
                            </div>
                        </div>
                    </div>
                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">가격</span>
                            {{form.price}}
                        </div>
                        {% if form.price.errors %}
                        {% for error in form.price.errors %}
                        <span class="text-red-700 font-medium text-sm">{{error}}</span>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">재고</span>
                            {{form.inventory}}
                        </div>
                        {% if form.inventory.errors %}
                        {% for error in form.inventory.errors %}
                        <span class="text-red-700 font-medium text-sm">{{error}}</span>
                        {% endfor %}
                        {% endif %}
                    </div>


                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">카테고리</span>
                            {{form.category}}
                            <div class="invalid-feedback">
                                상품 카테고리를 선택해주세요.
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품 설명</span>
                            {{form.description}}
                            <div class="invalid-feedback">
                                상품 설명을 입력해주세요.
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        <div class="input-group">
                            {{form.photo}}
                            <label class="input-group-text" for="fileInput">Upload</label>
                        </div>
                    </div>
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0">추가하기</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

minishop/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block page_title %}{{product.name}} 상세{% endblock page_title %}
{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            {% if messages %}
            {% for message in messages %}
            <div>
                {{ message|safe }}
            </div>
            {% endfor %}
            {% endif %}
            <span class="mb-3">{{product.category}} / {{product.name}}</span>
            <!-- Product image-->
            <div class="col-md-6">
                {% if product.photo %}
                <img class="card-img-top mb-5 mb-md-0" src="{{ product.photo.url }}" alt="..." />
                {% else %}
                <img class="card-img-top" src="https://dummyimage.com/450x450/dee2e6/6c757d&text=None" alt="..." />
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="small mb-1">{{product.category}}</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <br>
                <div class="fs-5 mb-2">
                    <span>{{product.price}}원</span>
                </div>
                <div class="fs-6 mb-2">
                    <span>재고: {{product.inventory}}</span>
                </div>
                <div class="fs-6 mb-5">
                    <i class="fas fa-star text-warning"></i> {{ product.total_rating }}
                </div>
                <p class="lead">{{product.description}}</p>
                {% if product.inventory == 0 %}
                <button type="button" class="btn btn-outline-dark flex-shrink-0 " disabled>재고 부족</button>
                {% else %}
                <a href="{% url 'orders:create' product.pk %}" class="btn btn-outline-dark flex-shrink-0">
                    주문하기
                </a>
                {% endif %}

                {% if is_wish %}
                <a href="{% url 'wishs:delete' pk=product.pk %}" class="flex-shrink-0 align-middle ms-3">
                    <i class="fab fa-gratipay fa-2x text-danger"></i>
                </a>
                {% else %}
                <a href="{% url 'wishs:add' pk=product.pk %}" class="flex-shrink-0 align-middle ms-3">
                    <i class="fab fa-gratipay fa-2x text-dark"></i>
                </a>
                {% endif %}
            </div>
            {% if reviews %}
            <div class="col-12 mt-5">
                <h5>리뷰</h5>
                <ul class="list-group list-group-flush">
                    {% for review in reviews %}
                    <li class="list-group-item d-flex justify-content-between">
                        <div>
                            {{review.review}} ' <i class="fas fa-star text-warning"></i> {{review.rating}} '
                        </div>
                        <div>
                            {{review.created_at}}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

minishop/templates/products/product_list.html
{% extends 'base.html' %}
{% block page_title %}Home{% endblock page_title %}
{% block content %}

<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">데베로 조인</h1>
            <p class="lead fw-normal text-white-50 mb-0">2021-2 DataBase</p>
        </div>
    </div>
</header>
{% if messages %}
{% for message in messages %}
<div>
    {{ message|safe }}
</div>
{% endfor %}
{% endif %}
<!-- Section-->
<section class="pt-5 pb-3">
    <div class="container px-4 px-lg-5 mt-5">
        <h1 class="mb-4">New</h1>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <figure class="image_wrapper">
                        {% if product.photo %}
                        <img class="card-img-top mb-5 mb-md-0 child" src="{{ product.photo.url }}" alt="..." />
                        {% else %}
                        <img class="card-img-top child" src="https://dummyimage.com/500x500/dee2e6/6c757d&text=None"
                            alt="..." />
                        {% endif %}
                    </figure>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{product.name}}</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            <div>
                                {{product.price}} 원
                            </div>
                            <!-- Product Inventory-->
                            <div>
                                재고: {{product.inventory}}
                            </div>
                            <div>
                                <i class="fas fa-star text-warning"></i> {{product.total_rating}}
                            </div>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                href="{% url 'products:detail' pk=product.pk %}">상품 상세페이지</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Paginator -->
<div class="d-flex justify-content-center">
    <ul class="pagination ">
        <!-- 이전 페이지 -->
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previous_page_number}}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link">Previous</a>
        </li>
        {% endif %}


        <!-- 페이지 링크들 -->
        {% for n in page_obj.paginator.page_range %}
        {% if page_obj.number == n %}
        <li class="page-item active">
            <span class="page-link">{{ n }}</span>
        </li>
        {% elif n > page_obj.number|add:'-5' and n < page_obj.number|add:'5' %} <li class="page-item">
            <a class="page-link" href="?page={{ n }}">{{ n }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{page_obj_name.next_page_number}}" class="page-link">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">Next</a>
            </li>
            {% endif %}
    </ul>
</div>
{% endblock %}

minishop/templates/products/product_manage.html
{% extends 'base.html' %}
{% block page_title %}스태프 페이지{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    {% include 'users/partials/staff_navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4 d-flex justify-content-between">
            <div>
                <h3>상품 관리</h3>
            </div>
            {% if messages %}
            {% for message in messages %}
            <div>
                {{ message|safe }}
            </div>
            {% endfor %}
            {% endif %}
            <div>
                <a href="{% url 'products:create' %}" class="btn btn-outline-dark flex-shrink-0">
                    상품추가
                </a>
            </div>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <div>
                <table class="table align-middle text-nowrap">
                    <thead>
                        <tr>
                            <th style="width:50px" class="text-center" scope="col">상품번호</th>
                            <th style="width:300px" class="text-center" scope="col">상품명</th>
                            <th style="width:100px" class="text-center" scope="col">가격</th>
                            <th style="width:100px" class="text-center" scope="col">재고</th>
                            <th style="width:150px" class="text-center" scope="col">카테고리</th>
                            <th style="width:100px" class="text-center" scope="col">단종여부</th>
                            <th style="width:100px" class="text-center" scope="col">수정</th>
                            <th style="width:100px" class="text-center" scope="col">삭제</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in product_list %}
                        <tr>
                            <td class="text-center">{{product.pk}}</td>
                            <td class="text-center text-decoration-none"><a
                                    href="{% url 'products:detail' pk=product.pk %}"
                                    class=" text-decoration-none text-black fw-bolder">{{product.name}}</a></td>
                            <td class="text-center">{{product.price}}</td>
                            <td class="text-center">{{product.inventory}}</td>
                            <td class="text-center">{{product.category}}</td>
                            <td class="text-center">{{product.discontinue}}</td>
                            <td class="text-center"><a href="{% url 'products:update' pk=product.pk %}"
                                    class="btn btn-outline-dark flex-shrink-0">
                                    수정</a>
                            </td>
                            <td class="text-center"><a href="{% url 'products:delete' pk=product.pk %}"
                                    class="btn btn-outline-dark flex-shrink-0">
                                    삭제</a>
                            </td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>




        <!-- Paginator -->
        <div class="d-flex justify-content-center">
            <ul class="pagination ">
                <!-- 이전 페이지 -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{page_obj.previous_page_number}}" class="page-link">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                {% endif %}


                <!-- 페이지 링크들 -->
                {% for n in page_obj.paginator.page_range %}
                {% if page_obj.number == n %}
                <li class="page-item active">
                    <span class="page-link">{{ n }}</span>
                </li>
                {% elif n > page_obj.number|add:'-5' and n < page_obj.number|add:'5' %} <li class="page-item"><a
                        class="page-link" href="?page={{ n }}">{{ n }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 -->
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{page_obj.next_page_number}}" class="page-link">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">Next</a>
                    </li>
                    {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

minishop/templates/products/product_update.html
{% extends 'base.html' %}
{% block page_title %}상품 수정{% endblock page_title %}
{% block content %}
<div class="d-flex container mt-5">
    {% include 'users/partials/staff_navbar.html' %}
    <div class="container-fluid d-flex flex-column justify-content-between align-center" style=" width:1000px;">
        <div class="mb-4 d-flex justify-content-between">
            <h3>상품 수정</h3>
        </div>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}
        <div class="d-flex justify-content-between mb-4">
            <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품명</span>
                            {{form.name}}
                            <div class="invalid-feedback">
                                상품명을 입력해주세요
                            </div>
                        </div>
                    </div>
                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">가격</span>
                            {{form.price}}
                            <div class="invalid-feedback">
                                가격을 입력해주세요
                            </div>
                        </div>
                    </div>
                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">재고</span>
                            {{form.inventory}}
                            <div class="invalid-feedback">
                                재고를 입력해주세요
                            </div>
                        </div>
                    </div>


                    <div class="col-4 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">카테고리</span>
                            {{form.category}}
                            <div class="invalid-feedback">
                                상품 카테고리를 선택해주세요.
                            </div>
                        </div>
                    </div>

                    <div class="col-12 mb-3">
                        <div class="input-group has-validation">
                            <span class="input-group-text">상품 설명</span>
                            {{form.description}}
                            <div class="invalid-feedback">
                                상품 설명을 입력해주세요.
                            </div>
                        </div>
                    </div>
                    <div class="col-12 mb-3">
                        {{form.photo}}
                    </div>
                    <div class="col-12 mb-3">
                        <div class="form-check">
                            {{form.discontinue}}
                            <label class="form-check-label" for="discontinueInput">
                                단종 여부
                            </label>
                        </div>
                    </div>
                </div>
                <div class="text-end mt-4">
                    <button class="btn btn-outline-dark flex-shrink-0">수정하기</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}